apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project1.apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: infra
  source:
    helm:
      valueFiles:
        - values.project1.yaml
    path: argocd-gitops-apps
    repoURL: git@github.com:ismoilovfk/gitops.git
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true