{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ . }}.{{ $.Values.stage }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $.Values.namespace }}
    server: {{ $.Values.server }}
  project: {{ $.Values.project }}
  source:
    helm:
      valueFiles:
      - {{ . }}.{{ $.Values.stage }}.yaml
    path: {{ $.Values.path }}
    repoURL: {{ $.Values.repo }}
    targetRevision: {{ $.Values.stage }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}